### ISSUE TITLE
AoC BYOS: bring your own solution!

### ISSUE THREAD

**Issue by fjebaker** [astro-group-bristol/developer-group#1]
Let's all do the [first Advent of Code](https://adventofcode.com/) on the 1st of December, and share our solutions at the next meetup!

**Comment by mbtaylor** [comment]
My solutions in java and rust (for day 1 anyway) at https://github.com/mbtaylor/experiment/

**Comment by fjebaker** [comment]
My (awful) scheme solutions will be posted here until I inevitably give up on the language
- https://github.com/fjebaker/advent-of-code-2023

**Comment by phajy** [comment]
I'm on the train so missed the meet-up but here's my go at day #1

https://github.com/phajy/AdventOfCode23.git

Even day 1 is a bit tricky. Not sure I'll be able to restore snow operations before the 25th. Yikes.

**Comment by RhysAlfShaw** [comment]
Working on day 2 now, all my solutions will be here.
[https://github.com/RhysAlfShaw/AdventofCode](https://github.com/RhysAlfShaw/AdventofCode)
