### ISSUE TITLE
How to make a free PIMPING website with GitHub pages

### ISSUE THREAD

**Issue by RhysAlfShaw** [astro-group-bristol/developer-group#12]
Some might be interested in how they can have a free personal static website using github pages.

**Comment by fjebaker** [comment]
This would be super useful! Maybe also in the context of CI/CD with #4 ?

**Comment by fjebaker** [comment]
Hi @RhysAlfShaw would you be available to run this (~15-20 mins) on February 9th?

**Comment by RhysAlfShaw** [comment]
Yes I can do that!🤌

**Comment by phajy** [comment]
I think it is also possible to get the code documentation and doc strings, etc., to convert into GitHub pages. Could this be covered too, if anyone knows how it works?

**Comment by fjebaker** [comment]
Material: https://github.com/astro-group-bristol/intro-to-githubpages
