### ISSUE TITLE
Regex?

### ISSUE THREAD

**Issue by HallJoseph** [astro-group-bristol/developer-group#14]
As discussed at coffee today (2024-01-23) it could be worth having a look at how to use regex. It may not be useful to any of our work but it is a useful thing to know.

**Comment by mbtaylor** [comment]
https://xkcd.com/208/

**Comment by fjebaker** [comment]
Hi @HallJoseph would you like to lead the discussion on regex? Maybe some short 10-15 intro to what is regex, why we might want to use it, and maybe some tools for using regex?

**Comment by HallJoseph** [comment]
Hi @fjebaker, I should be able to yeah! When would be a good time to do it?

**Comment by fjebaker** [comment]
Would Feb 16th be alright?

**Comment by HallJoseph** [comment]
Should be, I may need to postpone it though. I'll let you know if anything does change.

**Comment by fjebaker** [comment]
I'll pencil you in then :shipit:

**Comment by HallJoseph** [comment]
[
[RegEx for Astronomers.pptx](https://github.com/astro-group-bristol/developer-group/files/14266400/RegEx.for.Astronomers.pptx)
](url)
