### ISSUE TITLE
Parallelising Code

### ISSUE THREAD

**Issue by lucyastro** [astro-group-bristol/developer-group#17]
Looking at all things parallelisation would be really helpful. I have started experimenting and reading about this myself but any tips and best practices would be much appreciated!

**Comment by phajy** [comment]
I'd also be interested in finding out how multi-threading works in different languages (including Julia), and specifically how function calls are handled. I am aware that "it is notoriously difficult to write correct and data-race free multi-threaded code" and would like to know some simple tricks for avoiding these problems (even if the resulting code isn't as efficient as it could possibly be). Better to be slower and right than faster and wrong!

**Comment by fjebaker** [comment]
Hi @lucyastro ! Would you like to lead a discussion on this?

**Comment by RhysAlfShaw** [comment]
I am happy to do a session on this and the ways I have used to do some parallelising  in python using Mulitiprocessing, Cupy and numba.

**Comment by fjebaker** [comment]
https://github.com/astro-group-bristol/parallelising-python material from @RhysAlfShaw presentation
