### ISSUE TITLE
Profiling with Flame Graphs

### ISSUE THREAD

**Issue by mbtaylor** [astro-group-bristol/developer-group#19]
[Flame Graphs](https://www.brendangregg.com/flamegraphs.html) are a neat tool for finding out where your code is spending time/resources, which you need to know if you want to improve performance.

Generating them tends to be quite platform-specific, but I could give an introduction to what they look like and show some examples.

**Comment by fjebaker** [comment]
Brendan Gregg is such a cool guy! Yes this would be very cool!

**Comment by fjebaker** [comment]
Hi Mark! Would you be available to lead a discussion on this on the 15th of March?

**Comment by mbtaylor** [comment]
Will do.

**Comment by mbtaylor** [comment]
@fjebaker I was going to add a repository here with some presentation materials; I think I need to be an astro-group-bristol member for that, can you fix it for me?

**Comment by fjebaker** [comment]
@mbtaylor You should have received an invite now!

**Comment by mbtaylor** [comment]
Materials at https://github.com/astro-group-bristol/profiling-with-flamegraphs
