### ISSUE TITLE
Common git / GitHub CLI errors

### ISSUE THREAD

**Issue by lucyastro** [astro-group-bristol/developer-group#20]
Common errors when trying to remotely interact with GitHub on local machine command line.

**Comment by fjebaker** [comment]
Hi @lucyastro would you be happy to lead a discussion on this on the 8th of March?

**Comment by lucyastro** [comment]
Yes that's fine :) I don't know if it would take the whole meeting though, so might be good to have another short discussion on the agenda.

**Comment by lucyastro** [comment]
Material: 
[DevGroup_0803.pptx](https://github.com/astro-group-bristol/developer-group/files/14935627/DevGroup_0803.pptx)
[git_SSH_setup.pdf](https://github.com/astro-group-bristol/developer-group/files/14935769/git_SSH_setup.pdf)
