### ISSUE TITLE
The trials and tribulations of teaching coding units

### ISSUE THREAD

**Issue by DrMaireGorman** [astro-group-bristol/developer-group#22]
Hi everyone

It has been on my conscious that I should really try to contribute a session myself to this wonderful group :-) I am super-rusty at coding and don't have any specialist technical knowledge that group members wouldn't already know.

Would a session/discussion on teaching coding be of interest/useful? I could put together slides on background educational methods/frameworks/constraints/history. 

One of the best teaching CPD which have ever come across was  this - we could maybe have an AA-type discussion on issues/student mindsets encountered and ways to make things better?
"Failures, Fiascos and F**k Ups: Improving our practice by reflecting on our mistakes"

https://www.aber.ac.uk/en/is/it-services/elearning/networks-and-events/networks-and-events-learning-teaching-conference/conferencearchive2019/#d.en.228895

P.S Away in Brighton on Fri 22nd but could **maybe** do remotely if nothing else. 

Maire
P.S. Can't figure out how to put label of "meet-up-suggestion"

**Comment by fjebaker** [comment]
Hi @DrMaireGorman this sounds like a really good discussion! If you are away on the 22nd, would April 5th or 12th work for you?

**Comment by DrMaireGorman** [comment]
Either 5th or 12th April would work for me :-)  Slot me in whenever works for group. 
Maire

**Comment by fjebaker** [comment]
I'll pencil you in for the 5th then. Thanks!

**Comment by fjebaker** [comment]
Thanks again @DrMaireGorman ! This was a super presentation, and a really engaging discussion!
