### ISSUE TITLE
SQL (and ADQL and TAP)

### ISSUE THREAD

**Issue by mbtaylor** [astro-group-bristol/developer-group#28]
I could talk about using SQL (Structured Query Language) to interrogate databases.

Warning: I will probably use this as an excuse to show how you can query remote astronomy archives using TOPCAT via the Virtual Observatory's Table Access Protocol, which uses the ADQL dialect of SQL.

**Comment by fjebaker** [comment]
Hi @mbtaylor that would be brilliant! Would Friday May 3rd suit you?

**Comment by mbtaylor** [comment]
Yes Fri 3 May should be OK.

**Comment by mbtaylor** [comment]
Slides here: [sql.pdf](https://github.com/astro-group-bristol/developer-group/files/15199523/sql.pdf)
