### ISSUE TITLE
Topic suggestion: Automated workflows

### ISSUE THREAD

**Issue by phajy** [astro-group-bristol/developer-group#5]
Hattie mentioned some automated workflows to format code, etc. before pushing to GitHub. I'd like to hear more about those.

Perhaps there are other automated workflows that are similarly interesting.

**Comment by fjebaker** [comment]
Yes I would too! @hstewart93 would you be interested in doing a wee 15 minute demonstration of how to use your git hooks tool in an upcoming meeting?

**Comment by hstewart93** [comment]
Happy to give a little demo on this, it's pretty easy to set up with `pre-commit`, but I can talk about linting and autoformatting at the same time. You will need a `.pre-commit-config.yaml` file, I can put an example set up somewhere @fjebaker if you tell me where is useful?

**Comment by phajy** [comment]
> You will need a `.pre-commit-config.yaml` file, I can put an example set up somewhere @fjebaker if you tell me where is useful?

Maybe we could also have a discussion about the best way to organise the repository. E.g., should we organise by date or topic? Or by person / something completely different. What do you think, @fjebaker, @hstewart93, or anyone else?

**Comment by fjebaker** [comment]
> Maybe we could also have a discussion about the best way to organise the repository.

Yes agreed. I was hoping to save that discussion until after we've done a short intro to git, as it means we can all then contribute to the organisation of the repository. 

Maybe that's what we can do in the last meetup before the break? Start the new year with proper organisation!

**Comment by fjebaker** [comment]
At the moment, I think it would be better to create an example repo in the organisation for specific things, e.g. for the `.pre-commit-config.yml` example. We can add one here later, but then that one should be tailored for the needs of this repository, and is maybe not the best way to illustrate what you can do with pre-commit hooks -- if that's alright with you? Also would be fine to have everything in one place is that's preferred by others!

**Comment by phajy** [comment]
Thanks @hstewart93 for leading the discussion on this and setting up the corresponding [dev-tools repository](https://github.com/astro-group-bristol/dev-tools).

Here are the tools Hattie introduced:

- [pre-commit](https://pre-commit.com) - A framework for managing and maintaining multi-language pre-commit hooks
- [Flake8](https://flake8.pycqa.org/en/latest/) - Your Tool For Style Guide Enforcement
- [Black](https://black.readthedocs.io/en/stable/) - The uncompromising code formatter

More info in the [README](https://github.com/astro-group-bristol/dev-tools/blob/main/README.md)!

**Comment by fjebaker** [comment]
I am going to close this topic suggestion since Hattie presented last week :)

**Comment by fjebaker** [comment]
Material: https://github.com/astro-group-bristol/python-template
