### ISSUE TITLE
Git Workflows

### ISSUE THREAD

**Issue by hstewart93** [astro-group-bristol/developer-group#6]
Might be useful to talk about branching/useful commit messages etc and just general git practices to make the most of the tool?

**Comment by phajy** [comment]
Yes, that sounds very good. Also, code reviews within the group, as you suggested (part of general git practices)?

**Comment by hstewart93** [comment]
Yeah for sure that can all get wrapped up in there.

**Comment by grant-m-s** [comment]
would definitely recommend: https://learngitbranching.js.org/

**Comment by hstewart93** [comment]
@fjebaker I won't be here next week I'm afraid, happy to do another Friday though

**Comment by mbtaylor** [comment]
29 March is Good Friday!  University closed.

**Comment by fjebaker** [comment]
@hstewart93 19th of April okay?
