### ISSUE TITLE
Speeding up sparse convolutions: placement experience

### ISSUE THREAD

**Issue by fjebaker** [astro-group-bristol/developer-group#65]
Grant will tell us about what he did during his placement.

**Comment by grant-m-s** [comment]
For those interested the talk will cover topics including:
- How Pytorch performs Convolutions under-the-hood
- Implementation of novel methods that outperform default Pytorch implementations
- Code developed using CUDA and C++
- How LiDAR is processed in autonomous vehicles
- Optimising processes for computing on the edge (high compute, low power)
- What is the process of getting a patent for a project (from the engineering perspective)

**Comment by grant-m-s** [comment]
Not sure the extent at which the slides can be shared so i'd rather stay on the safe side and not share them out, sorry about that

**Comment by fjebaker** [comment]
No problem!
