### ISSUE TITLE
Graphviz / Mermaid / Inkscape

### ISSUE THREAD

**Issue by RhysAlfShaw** [astro-group-bristol/developer-group#68]
Astronvim - https://astronvim.com/

**Comment by RhysAlfShaw** [comment]
Graphziv - https://graphviz.org/

**Comment by RhysAlfShaw** [comment]
Inkscape - https://inkscape.org

**Comment by RhysAlfShaw** [comment]
Mermaid - https://mermaid.js.org/

**Comment by fjebaker** [comment]
```mermaid
graph TD;
    A --> B;
```

**Comment by fjebaker** [comment]
[Draw IO](https://draw.io)

**Comment by fjebaker** [comment]
https://castel.dev/post/lecture-notes-2/

**Comment by fjebaker** [comment]
https://css-tricks.com/accessible-svgs/
