### ISSUE TITLE
XMM Data Reduction

### ISSUE THREAD

**Issue by fjebaker** [astro-group-bristol/developer-group#69]
Putting it in the schedule for next week. Please post resources and links in this issue.

**Comment by TomHigginson** [comment]
I have attached the slides for the presentation 
[here](https://github.com/user-attachments/files/17720295/XMM_Reduction_Presentation.pdf).

I have also linked to the [data reduction](https://github.com/astro-group-bristol/reduction-scripts) script repository.

**Comment by fjebaker** [comment]
Brilliant! Thanks!
