### ISSUE TITLE
XGA and DAXA

### ISSUE THREAD

**Issue by fjebaker** [astro-group-bristol/developer-group#70]
Putting this in for the 29th, is that alright @HallJoseph ?

**Comment by fjebaker** [comment]
Thanks again @HallJoseph ! Do let me know if you can share slides / material :)

**Comment by HallJoseph** [comment]
Hi @fjebaker, I'll ask Jess -- is it possible to set the files to private so only group members can see?

**Comment by fjebaker** [comment]
@HallJoseph not for the time being. If they can't be public, then no problem! :+1:

**Comment by HallJoseph** [comment]
Link here: https://github.com/astro-group-bristol/xga_daxa_demo
