### ISSUE TITLE
GitHub branches fork (other than the main branch)

### ISSUE THREAD

**Issue by GloriaRAH** [astro-group-bristol/developer-group#8]
Supposing you forked a GitHub repository and only forked the main branch.
The original repository now has new branches that you want to fork in your repository. 
However, even if you synchronise your fork, you don't get the new branches.
How to get these new branches into your repository?

**Comment by fjebaker** [comment]
Try this:
```bash
git remote add upstream <url-of-the-upstream-repo>
git fetch --all
git push <my-fork> <branch-name>
```
