### ISSUE TITLE
Catalogue Matching

### ISSUE THREAD

**Issue by HallJoseph** [astro-group-bristol/developer-group#81]
The green line should not go up. 

The green line does go up.

[F500_completeness_n_clust_for_clumpr_full_erass_new_dz.pdf](https://github.com/user-attachments/files/18128707/F500_completeness_n_clust_for_clumpr_full_erass_new_dz.pdf)

:(

**Comment by HallJoseph** [comment]
I have fixed this, there was a simple error in my code with an inequality the wrong way around 🙃

Green line no longer goes up.

[F500_completeness_n_clust_for_clumpr_full_erass_ineeq_fix_new_dz.pdf](https://github.com/user-attachments/files/18149903/F500_completeness_n_clust_for_clumpr_full_erass_ineeq_fix_new_dz.pdf)

**Comment by fjebaker** [comment]
Classic! Glad you were able to resolve it!
